### PR TITLE
update to futures 0.3.1(fix issue #37)

### PR DESCRIPTION
**Pull request by jerry73204**
This PR relates to #37. It updates to `futures-preview` to `futures` 0.3.1 and fixes incompatibility changes.

### CODE REVIEW

**Comment by brunocodutra** [comment]
Great stuff, thanks!
I wonder why github actions didn't run, any clue?

**Comment by jerry73204** [comment]
Should I do anything manually for you?

**Comment by brunocodutra** [comment]
No worries, I'll manually merge this one and try to fix the issue with CI for future PRs. Hopefully I can have a look at this later today.

**Comment by brunocodutra** [comment]
@jerry73204 I finally got around to work on this and it seems your changes are [failing the Clippy check](https://github.com/brunocodutra/ring-channel/commit/6d7523885b723c3d1e58910ec7483cdb9521c944/checks?check_suite_id=374948920#step:4). Do you think you can have a look at this?

**Pull request closed without merging**
